### ISSUE TITLE
Wrong URL in repository for package.json

### ISSUE THREAD

**Issue by indexzero** [githulks/githulk#46]
See: https://github.com/githulks/githulk/blob/master/package.json#L11

``` js
  "repository": {
    "type": "git",
    "url": "http://github/3rd-Eden/githulk"
  },
```

`"url"` is missing `.com` ... sorry I didn't have a chance to make a PR yet, but wanted to report the issue before I forgot.

**Comment by jcrugzz** [comment]
Fixed in #47
