### ISSUE TITLE
Deduping of requests in mana is innapropriate for graphql endpoint

### ISSUE THREAD

**Issue by jcrugzz** [githulks/githulk#86]
The smart deduping of requests in mana doesnt consider the parameters given for the graphql query. This results in needing to force serial execution for hitting the graphql endpoint in order to ensure correct responses. Posting this for visibility until I have time to tackle it or someone gets to it before me. cc @indexzero @3rd-Eden

**Comment by indexzero** [comment]
Fixed by https://github.com/3rd-Eden/mana/pull/17 and bump in our upstream
